import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import ClientOnly from './components/ClientOnly'
import { Providers } from '@/redux/provider'
import Modal from './components/modal/Modal'
import UserList from './components/UserList'

const font = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Safari stay',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
        <ClientOnly>
         
      <Navbar/>
      <Modal actionLabel="button"   title= "Naivasha Nest"/>
      <UserList/>

      </ClientOnly>
        {children}


     </Providers>
      
      </body>

    </html>
  )
}
